class version:
    package = '0.2.0'
    InterfacesInfos = '1.5'
    InterfacesRoutes = '1.2'
    IfaceInfoTools = '0.6'
    FileReader = '0.2'
    Conn = '1.4'
    TCPConn = '1.2'
    UDPConn = '1.3'
    TCP6Conn = '1.0'
    UDP6Conn = '1.0'